# Generated by Django 4.2.5 on 2023-12-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tasklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('assingned_to', models.CharField(max_length=200)),
                ('assigned_by', models.CharField(max_length=200)),
                ('review', models.BooleanField(default=False)),
                ('priority', models.CharField(max_length=200)),
            ],
        ),
    ]
